#!/bin/zsh
# `tre` is a shorthand for `tree`, embracing the power of exa (via `exa -T`),
# while showing hidden files and ignoring some directories
#
# The depth of recursion can be set via a parameter, e.g. `tre 2`, `tre 4`, etc.
tre() {
	exa -T -a -L=${1:-1} -I='node_modules|bower_components|.git'
}
