#!/usr/bin/env bash

npm install -g npm-windows-upgrade

# For windows read the readme after you install this
npm install -g node-gyp

# Run this after installing node-gyp
npm install -g node-gyp-install

npm install -g npm-check
npm install -g updtr

npm install -g frctl/fractal;
npm install -g angular-cli;
npm install -g asar;
npm install -g ava;
npm install -g bootlint;
npm install -g bower;
npm install -g browserify;
npm install -g clean-css-cli;
npm install -g clipboard-cli;
npm install -g colorguard;
npm install -g critical;
npm install -g cross-env;
npm install -g csslint;
npm install -g diffchecker;
npm install -g doiuse;
npm install -g electron;
npm install -g ember-cli;
npm install -g emoj;
npm install -g eslint;
npm install -g eslint-config-airbnb;
npm install -g eslint-config-airbnb-base;
npm install -g eslint-plugin-import;
npm install -g eslint-plugin-jsx-a11y;
npm install -g eslint-plugin-react;
npm install -g express-generator;
npm install -g fast-cli;
npm install -g firebase-tools;
npm install -g generator-generator;
npm install -g generator-hubot;
npm install -g generator-webapp;
npm install -g generator-webapp-boilerplate;
npm install -g git-stats;
npm install -g grunt-cli;
npm install -g gulp-cli;
npm install -g hotel;
npm install -g hpm-cli;
npm install -g http-server;
npm install -g ipify;
npm install -g is-http2-cli;
npm install -g istanbul;
npm install -g jasmine;
npm install -g jscs;
npm install -g jsfmt;
npm install -g karma-cli;
npm install -g keybase-installer;
npm install -g lasso-cli;
npm install -g lighthouse;
npm install -g local-web-server;
npm install -g lodash-cli;
npm install -g mocha;
npm install -g nativefier;
npm install -g nodemon;
npm install -g now;
npm install -g now-serve;
npm install -g np;
npm install -g optimize-js;
npm install -g pa11y;
npm install -g pagexray;
npm install -g parker;
npm install -g plato;
npm install -g pm2;
npm install -g protractor;
npm install -g psi;
npm install -g pwmetrics;
npm install -g react-tools;
npm install -g recess;
npm install -g release;
npm install -g rxjs;
npm install -g sassdoc;
npm install -g serve;
npm install -g sitespeed.io;
npm install -g stylelint;
npm install -g taunus;
npm install -g textlint;
npm install -g timee;
npm install -g tmi;
npm install -g tslint;
npm install -g typescript;
npm install -g typings;
npm install -g uncss;
npm install -g vorlon;
npm install -g vue-cli;
npm install -g webcoach;
npm install -g webpack;
npm install -g webpack-dev-server;
npm install -g webpagetest;
npm install -g xo;
npm install -g yo;
