#!/bin/bash

npm i -g \
	node-gyp \
	@11ty/eleventy \
	@lhci/cli \
	@radum/eslint-config \
	@sitespeed.io/throttle \
	@squoosh/cli \
	@vue/cli \
	alfred-emoj \
	commitizen \
	cross-env \
	doctoc \
	emoj \
	eslint \
	eslint-config-airbnb \
	eslint-plugin-jsx-a11y \
	eslint-plugin-react \
	eslint-config-airbnb-base \
	eslint-config-kentcdodds \
	eslint-formatter-pretty \
	eslint-plugin-compat \
	eslint-plugin-eslint-comments \
	eslint-plugin-import \
	eslint-plugin-node \
	eslint-plugin-promise \
	eslint-plugin-unicorn \
	stylelint \
	ndb \
	tldr \
	np \
	jsonlint \
	rollup \
	sitespeed.io \
	git-stats \
	gulp-cli \
	lerna \
	lighthouse \
	local-web-server \
	nodemon \
	npm-check-updates \
	pm2 \
	prettier \
	rollup \
	sassdoc \
	sitespeed.io \
	terser \
	typescript \
	updtr \
	webpack-cli \
	webpack \
	webpack-dev-server \
	webpagetest
