#:schema https://mise.jdx.dev/schema/mise.json

[tools]
# Cargo augmenting tools
cargo-binstall = "latest"
cargo-insta = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-edit" = "latest"

# Software verification (see https://mise.jdx.dev/tips-and-tricks.html#software-verification)
slsa-verifier = "latest"
cosign = "latest"

# Provides completion and parsing support for tasks see:
# https://mise.jdx.dev/tasks/file-tasks.html#arguments
usage = "latest"

# Core tools
go = "latest"
node = "latest"
python = "latest"
rust = { version = "latest", components = "rust-analyzer,clippy" }
uv = "latest"
bun = "latest"
# This will fail to install on Linux as supported platforms are darwin, windows and amd64. But do I need it?
# ruby = "latest"
# zig = "latest"
