#!/bin/bash
#
# Run all dotfiles installers.
set -e

# Load UTILS
. "$DOTFILES/scripts/utils.sh"

info "> going back to root folder from $(dirname "$0")"
cd "$(dirname "$0")"/..

# find the installers and run them iteratively
info "> find the installers and run them iteratively"
git ls-tree --name-only -r HEAD | grep install.sh | while read -r installer; do
	echo ""
	info "› ${installer}..."
	sh -c "$installer"
done
