#!/bin/bash
# SPACESHIP_CHAR_SYMBOL=»
# SPACESHIP_CHAR_SYMBOL=➜
# SPACESHIP_CHAR_SYMBOL=❯
# shellcheck disable=SC2034
SPACESHIP_CHAR_SYMBOL=λ
# shellcheck disable=SC2034
SPACESHIP_CHAR_SUFFIX=" "
export REPORTTIME=10
