# TODO: Symlink this to ~/.config/starship.toml
# Get editor completions based on the config schema
# "$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Timeout for commands executed by starship (in milliseconds).
command_timeout = 650

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[»](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

# A continuation prompt that displays two filled in arrows
continuation_prompt = '▶▶ '
